spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/morse?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://122.51.212.44:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: '@project.artifactId@'

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
