spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启Eureka服务发现
          lower-case-service-id: true
      routes:
        - id: userService
          uri: lb://morse-user
          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: '@project.artifactId@'

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug
